// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth-service.proto

package ppauth

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	AllowedRoles         []string `protobuf:"bytes,2,rep,name=allowedRoles,proto3" json:"allowedRoles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40c3308acdd691b6, []int{0}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthRequest) GetAllowedRoles() []string {
	if m != nil {
		return m.AllowedRoles
	}
	return nil
}

type AuthResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_40c3308acdd691b6, []int{1}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *AuthResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthRequest)(nil), "ppauth.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "ppauth.AuthResponse")
}

func init() { proto.RegisterFile("auth-service.proto", fileDescriptor_40c3308acdd691b6) }

var fileDescriptor_40c3308acdd691b6 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x31, 0x6f, 0x83, 0x30,
	0x10, 0x46, 0x0b, 0x55, 0x69, 0xb9, 0x32, 0x5d, 0x51, 0x65, 0x75, 0x42, 0x9e, 0x58, 0xca, 0xd0,
	0x2e, 0x1d, 0x1b, 0x65, 0xc8, 0xee, 0xfc, 0x02, 0x42, 0x4e, 0x21, 0xc2, 0xc1, 0x0e, 0x67, 0x27,
	0x7f, 0x3f, 0x02, 0x13, 0x29, 0x8c, 0xef, 0x0d, 0xf7, 0xbd, 0x03, 0xac, 0xbd, 0x6b, 0xbf, 0x99,
	0x86, 0xcb, 0xb1, 0xa1, 0xca, 0x0e, 0xc6, 0x19, 0x4c, 0xac, 0x1d, 0xad, 0xdc, 0xc0, 0xfb, 0xca,
	0xbb, 0x56, 0xd1, 0xd9, 0x13, 0x3b, 0xcc, 0xe1, 0xc5, 0x99, 0x8e, 0x7a, 0x11, 0x15, 0x51, 0x99,
	0xaa, 0x00, 0x28, 0x21, 0xab, 0xb5, 0x36, 0x57, 0xda, 0x2b, 0xa3, 0x89, 0x45, 0x5c, 0x3c, 0x97,
	0xa9, 0x5a, 0x38, 0xf9, 0x0f, 0x59, 0x38, 0xc4, 0xd6, 0xf4, 0x4c, 0xf8, 0x09, 0xc9, 0x40, 0xec,
	0xb5, 0x9b, 0x4e, 0xbd, 0xa9, 0x99, 0x50, 0xc0, 0xeb, 0x89, 0x98, 0xeb, 0x03, 0x89, 0x78, 0xda,
	0xb8, 0xe3, 0xcf, 0x9c, 0xb2, 0x0d, 0x9d, 0xf8, 0x07, 0xe9, 0xba, 0xa5, 0xa6, 0x1b, 0x1d, 0x7e,
	0x54, 0xa1, 0xb7, 0x7a, 0x88, 0xfd, 0xca, 0x97, 0x32, 0x0c, 0xcb, 0xa7, 0x5d, 0x32, 0xbd, 0xf8,
	0x7b, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x93, 0x0f, 0xd2, 0x68, 0xf8, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	CheckAuth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) CheckAuth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/ppauth.AuthService/CheckAuth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	CheckAuth(context.Context, *AuthRequest) (*AuthResponse, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) CheckAuth(ctx context.Context, req *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAuth not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_CheckAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CheckAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ppauth.AuthService/CheckAuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CheckAuth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ppauth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckAuth",
			Handler:    _AuthService_CheckAuth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth-service.proto",
}
